// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstatePortal.Data;

#nullable disable

namespace RealEstatePortal.Data.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260407102952_SeedRealEstates")]
    partial class SeedRealEstates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "33333333-3333-3333-3333-333333333333",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RestDays")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WorkingDays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("WorkingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("WorkingHoursStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.AgentLanguage", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("AgentId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("AgentLanguages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Studio Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "1-Bedroom Apartment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "2-Bedroom Apartment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "3+ Bedroom Apartment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maisonette / Duplex"
                        },
                        new
                        {
                            Id = 6,
                            Name = "House"
                        },
                        new
                        {
                            Id = 7,
                            Name = "House Floor"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Villa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Land / Plot"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Commercial Space"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Garage / Parking"
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shumen"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Veliko Tarnovo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Blagoevgrad"
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elevator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Garage / Parking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Central Heating"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Security System"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Access Control"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thermal Insulation"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gas Heating"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gym / Fitness Center"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sports Facilities"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Smart Home"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Video Surveillance (CCTV)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Storage / Basement"
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateId");

                    b.HasIndex("UserId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Area")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("BathroomsCount")
                        .HasColumnType("int");

                    b.Property<int>("BedroomsCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ConstructionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exposure")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Furnishing")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("RealEstateFloor")
                        .HasColumnType("int");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.ToTable("RealEstates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f9c5b2a-8d1e-4f7a-b2c6-9e4a1d5c8b7f"),
                            Address = "bul. Cherni Vrah 45",
                            AgentId = new Guid("d7445e1e-e99e-4cae-82f4-515775351513"),
                            Area = 120m,
                            BathroomsCount = 2,
                            BedroomsCount = 3,
                            CategoryId = 1,
                            CityId = 1,
                            CompletionStatus = "Fully finished",
                            ConstructionType = "Brick",
                            ConstructionYear = 2022,
                            Description = "Spacious 3-bedroom apartment in a premium location with underground parking and 24/7 security.",
                            Exposure = "South",
                            Furnishing = "Unfurnished",
                            IsDeleted = false,
                            Price = 250000m,
                            RealEstateFloor = 5,
                            RoomsCount = 4,
                            Status = 0,
                            TotalFloors = 8,
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-47a8-9b0c-1d2e3f4a5b6c"),
                            Address = "ul. Ivan Vazov 12",
                            AgentId = new Guid("d7445e1e-e99e-4cae-82f4-515775351513"),
                            Area = 95m,
                            BathroomsCount = 1,
                            BedroomsCount = 2,
                            CategoryId = 2,
                            CityId = 2,
                            CompletionStatus = "Fully finished",
                            ConstructionType = "Brick",
                            ConstructionYear = 2015,
                            Description = "Cozy house in the central area. Recently renovated with a small private garden.",
                            Exposure = "East-West",
                            Furnishing = "Fully Furnished",
                            IsDeleted = false,
                            Price = 145000m,
                            RealEstateFloor = 1,
                            RoomsCount = 3,
                            Status = 0,
                            TotalFloors = 2,
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("7e8f9a0b-1c2d-43e4-85f6-7a8b9c0d1e2f"),
                            Address = "Briz, ul. Sveti Nikola",
                            AgentId = new Guid("d7445e1e-e99e-4cae-82f4-515775351513"),
                            Area = 70m,
                            BathroomsCount = 1,
                            BedroomsCount = 1,
                            CategoryId = 1,
                            CityId = 3,
                            CompletionStatus = "Ready for living",
                            ConstructionType = "Brick",
                            ConstructionYear = 2019,
                            Description = "Modern 1-bedroom apartment for rent with sea view. Fully furnished.",
                            Exposure = "South-East",
                            Furnishing = "Fully Furnished",
                            IsDeleted = false,
                            Price = 650m,
                            RealEstateFloor = 3,
                            RoomsCount = 2,
                            Status = 0,
                            TotalFloors = 5,
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("d4c3b2a1-6f5e-48a7-b0c9-d1e2f3a4b5c6"),
                            Address = "Mladost 4, Business Park",
                            AgentId = new Guid("72d70512-ee7b-4f2e-bd62-baf7773f85fd"),
                            Area = 155m,
                            BathroomsCount = 3,
                            BedroomsCount = 4,
                            CategoryId = 3,
                            CityId = 1,
                            CompletionStatus = "Fully finished",
                            ConstructionType = "Brick",
                            ConstructionYear = 2021,
                            Description = "Luxury penthouse right next to Business Park Sofia. Huge terrace and smart home system.",
                            Exposure = "South-West",
                            Furnishing = "Semi-furnished",
                            IsDeleted = false,
                            Price = 320000m,
                            RealEstateFloor = 11,
                            RoomsCount = 5,
                            Status = 0,
                            TotalFloors = 12,
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-4978-8c0b-a19b2c3d4e5f"),
                            Address = "Lazur, bl. 77",
                            AgentId = new Guid("72d70512-ee7b-4f2e-bd62-baf7773f85fd"),
                            Area = 65m,
                            BathroomsCount = 1,
                            BedroomsCount = 1,
                            CategoryId = 1,
                            CityId = 4,
                            CompletionStatus = "Fully finished",
                            ConstructionType = "Brick",
                            ConstructionYear = 1998,
                            Description = "Excellent investment property near the Sea Garden. Needs minor cosmetic repairs.",
                            Exposure = "North-East",
                            Furnishing = "Unfurnished",
                            IsDeleted = false,
                            Price = 115000m,
                            RealEstateFloor = 4,
                            RoomsCount = 2,
                            Status = 0,
                            TotalFloors = 6,
                            TransactionType = 0
                        },
                        new
                        {
                            Id = new Guid("5c6b7a89-0d1e-4f2a-93b4-c5d6e7f8a9b0"),
                            Address = "Trakia, bl. 100",
                            AgentId = new Guid("72d70512-ee7b-4f2e-bd62-baf7773f85fd"),
                            Area = 55m,
                            BathroomsCount = 1,
                            BedroomsCount = 1,
                            CategoryId = 1,
                            CityId = 2,
                            CompletionStatus = "Ready for living",
                            ConstructionType = "Panel",
                            ConstructionYear = 1985,
                            Description = "Affordable apartment for rent in a quiet neighborhood. Close to public transport and supermarkets.",
                            Exposure = "West",
                            Furnishing = "Basic Furniture",
                            IsDeleted = false,
                            Price = 400m,
                            RealEstateFloor = 2,
                            RoomsCount = 2,
                            Status = 0,
                            TotalFloors = 8,
                            TransactionType = 1
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstateFeature", b =>
                {
                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("RealEstateId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RealEstateFeatures");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstateImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateId");

                    b.ToTable("RealEstateImages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.UserFavoriteRealEstate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RealEstateId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("UserFavoriteRealEstates");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a29cf631-1bcf-41a2-82cf-79bbb98f9e00",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJTV77ZtEMelMd9UuE0oTawOSiCvzLiCRgByE+XrL67DDszJf50bxJHaaGAVY1en2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c0a31b3-a75a-4f46-97f5-915351a1ca84",
                            TwoFactorEnabled = false,
                            UserName = "admin@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Agent", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("RealEstatePortal.Data.Models.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.AgentLanguage", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.Agent", "Agent")
                        .WithMany("SpokenLanguages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.Language", "Language")
                        .WithMany("AgentLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Inquiry", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.RealEstate", "RealEstate")
                        .WithMany("Inquiries")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.ApplicationUser", "User")
                        .WithMany("Inquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RealEstate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstate", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.Agent", "Agent")
                        .WithMany("RealEstates")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.Category", "Category")
                        .WithMany("RealEstates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.City", "City")
                        .WithMany("RealEstates")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("City");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstateFeature", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.Feature", "Feature")
                        .WithMany("RealEstateFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.RealEstate", "RealEstate")
                        .WithMany("RealEstateFeatures")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstateImage", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.RealEstate", "RealEstate")
                        .WithMany("RealEstateImages")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.UserFavoriteRealEstate", b =>
                {
                    b.HasOne("RealEstatePortal.Data.Models.RealEstate", "RealEstate")
                        .WithMany("FavoriteRealEstates")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstatePortal.Data.Models.ApplicationUser", "User")
                        .WithMany("FavoriteRealEstates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Agent", b =>
                {
                    b.Navigation("RealEstates");

                    b.Navigation("SpokenLanguages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Category", b =>
                {
                    b.Navigation("RealEstates");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.City", b =>
                {
                    b.Navigation("RealEstates");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Feature", b =>
                {
                    b.Navigation("RealEstateFeatures");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.Language", b =>
                {
                    b.Navigation("AgentLanguages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.RealEstate", b =>
                {
                    b.Navigation("FavoriteRealEstates");

                    b.Navigation("Inquiries");

                    b.Navigation("RealEstateFeatures");

                    b.Navigation("RealEstateImages");
                });

            modelBuilder.Entity("RealEstatePortal.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FavoriteRealEstates");

                    b.Navigation("Inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
